name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
  - name: Deploy
    runs-on: ubuntu-latest
    steps:
    uses: flyweightrocks/aws-ec2-action@v1
    with:
      instance-id: ad
      wait-instance-running: true
      stop-instance: true
    run: aws ec2 start-instances --instance-ids ${{ secrets.AWS_INSTANCE_ID }}

    # - name: Deploy
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     AWS_DEFAULT_REGION: us-east-1
    #     #AWS_DEFAULT_OUTPUT: json

      #run: aws amplify start-job --app-id xxx --branch-name master --job-type RELEASE
