name: Hello World Schedule

name: "example-cron-action"
on:
  schedule:
    - cron:  '*/15 * * * *'    # At every 15th minute

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello World
      run: echo "Hola Mundo"
