name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: eu-east-1
        #AWS_DEFAULT_OUTPUT: json
      run: aws ec2 start-instances --instance-ids ${{ secrents.AWS_INSTANCE_ID }}

      #run: aws amplify start-job --app-id xxx --branch-name master --job-type RELEASE