name: AWS Action with OIDC

on:
  push:
    branches:
      - main

jobs:
  aws-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::618656345723:role/github-oidc-iam-role
          role-session-name: github-oidc-session-name
          aws-region: us-east-1 

      - name: Run AWS CLI command
        run: |
          aws s3 ls  # Ejemplo de un comando AWS

      
      # - name: aws start
      #   run: |
      #     aws ec2 start-instances --instance-ids i-05ce1aef9de4bff74
