name: Workflow 1

on:
  workflow_dispatch:  # Permite que se inicie manualmente desde la interfaz de GitHub Actions

jobs:
  build:
    name: First Job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run first action
      run: |
        echo "First job: Hello from job 1!"
        # Simular éxito
        echo "Job 1 completed successfully"

    - name: Save artifact for next workflow
      if: success()
      run: echo "success" > status.txt
      
    - name: Upload artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: workflow-1-status
        path: status.txt
